---

# file: roles/ansible-update_upgrade_reboot/tasks/main.yaml

- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ package_cache_valid_time }}"

- name: upgrade all packages
  apt:
    upgrade: "full"
    purge: true
    autoclean: true
    autoremove: true

- name: check if reboot is required
  stat:
    path: "{{ reboot_required_file }}"
  register: reboot_required

- name: restart server
  shell: sleep 3; shutdown -r now "Ansible updates triggered reboot"
  when: reboot_required.stat.exists
  async: true
  poll: 0
  ignore_errors: true
  register: rebooting

- name: wait for server to be back online (if rebooted)
  wait_for_connection:
    connection_timeout: "{{ reboot_wait_server_connection_timeout }}"
    delay: "{{ reboot_wait_delay }}"
    sleep: "{{ reboot_wait_interval }}"
    timeout: "{{ reboot_wait_timeout }}"
  when: rebooting is changed
