---

# file: roles/ansible-update_upgrade_reboot/tasks/main.yaml

- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ package_cache_valid_time }}"
  changed_when: false

- name: upgrade all packages
  apt:
    upgrade: "full"
    purge: true
    autoclean: true
    autoremove: true

- name: check if reboot is required
  stat:
    path: "{{ reboot_required_file }}"
  register: reboot_required

- name: restart server (if reboot required & allowed)
  shell: sleep 3; shutdown -r now "Ansible updates triggered reboot"
  when:
    - reboot_required.stat.exists
    - update_upgrade_reboot_allow_reboot|bool
  async: true
  poll: 0
  ignore_errors: true
  register: rebooting

- name: wait for server to be back online (if rebooted)
  wait_for_connection:
    connect_timeout: "{{ reboot_wait_server_connection_timeout }}"
    delay: "{{ reboot_wait_delay }}"
    sleep: "{{ reboot_wait_interval }}"
    timeout: "{{ reboot_wait_timeout }}"
  when:
    - rebooting is changed

- name: notice
  debug:
    msg: |
      WARNING: Reboot was required, but not allowed.
               Set 'update_upgrade_reboot_allow_reboot: True'
               in order to perform an automated reboot.
  when:
    - reboot_required.stat.exists
    - not update_upgrade_reboot_allow_reboot|bool
