---

# file: roles/ansible-update_upgrade_reboot/tasks/main.yaml

- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ update_upgrade_reboot_package_cache_valid_time }}"
  changed_when: false

- name: Upgrade all packages
  apt:
    upgrade: "full"
    purge: true
    autoclean: true
    autoremove: true
  retries: "{{ update_upgrade_reboot_max_retry_loops }}"
  delay: "{{ update_upgrade_reboot_retry_loop_delay }}"
  register: update_upgrade_reboot_wait_loop
  until: update_upgrade_reboot_wait_loop is succeeded

- name: Check if reboot is required
  stat:
    path: "{{ update_upgrade_reboot_restart_required_file }}"
  register: update_upgrade_reboot_restart_required

- name: Restart server (if reboot required & allowed)
  reboot:
    msg: "{{ update_upgrade_reboot_restart_message }}"
    post_reboot_delay: "{{ update_upgrade_reboot_wait_delay }}"
    reboot_timeout: "{{ update_upgrade_reboot_wait_timeout }}"
  when:
    - update_upgrade_reboot_restart_required.stat.exists
    - update_upgrade_reboot_allow_reboot|bool

- name: Notice
  debug:
    msg: |
      WARNING: Reboot was required, but not allowed.
               Set 'update_upgrade_reboot_allow_reboot: True'
               in order to perform an automated reboot.
  when:
    - update_upgrade_reboot_restart_required.stat.exists
    - not update_upgrade_reboot_allow_reboot|bool
